name: master_parenthood
description: AI-powered parenting assistant app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management & Dependency Injection
  provider: ^6.0.5
  get_it: ^7.6.7
  injectable: ^2.3.2

  # UI/UX
  flutter_animate: ^4.2.0
  fl_chart: ^0.64.0
  table_calendar: ^3.1.2
  url_launcher: ^6.1.14

  # Storage
  shared_preferences: ^2.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

  # Networking
  dio: ^5.3.2
  http: ^1.1.0

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.7.10
  google_sign_in: ^6.1.5

  # Utilities
  intl: ^0.20.2
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  share_plus: ^7.2.1
  connectivity_plus: ^5.0.2

  # Notifications & Local scheduling
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  workmanager: ^0.5.2

  # Voice & Speech
  speech_to_text: ^6.6.2
  flutter_tts: ^4.0.2
  permission_handler: ^11.3.1

  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/illustrations/
    - assets/splash/