name: master_parenthood
description: AI-powered parenting assistant app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  provider: ^6.0.5

  # UI/UX
  flutter_animate: ^4.2.0
  fl_chart: ^0.64.0

  # Storage
  shared_preferences: ^2.2.1

  # Networking
  dio: ^5.3.2

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.17.5
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^6.1.1

  # AI Integration (OpenAI)
  http: ^1.1.0

  # Utilities
  intl: ^0.20.2

  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true